default_settings: null
behaviors:
  FPSBot:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 10240
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      shared_critic: false
      learning_rate_schedule: constant
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      memory: null
        # memory_size: 64
        # sequence_length: 32
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.05
        gamma: 0.995
        learning_rate: 0.001
        network_settings:
          hidden_units: 256
          num_layers: 2
    #   gail:
    #     strength: 0.4
    #     gamma: 0.99
    #     demo_path: Assets/Demonstrations
    #     learning_rate: 0.0001
    #     network_settings:
    #       normalize: false
    #       hidden_units: 128
    #       num_layers: 2
    #       vis_encode_type: simple
    #     use_actions: false
    #     use_vail: false
    # behavioral_cloning:
    #   demo_path: Assets/Demonstrations
    #   steps: 50000
    #   strength: 0.4
    #   samples_per_update: 0
    #   init_path: null
    keep_checkpoints: 40
    checkpoint_interval: 200_000
    max_steps: 5_000_000
    time_horizon: 1000
    summary_freq: 5000
    threaded: true
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 2000
      team_change: 200000
      initial_elo: 1200
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: ppo
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false